### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by armagadon159753** [PMMPPlugin/VirtualChest#1]
`[00:24:42] [Server thread/CRITICAL]: Unhandled exception executing command 'vc open' in vchest: Argument 1 passed to pocketmine\inventory\BaseInventory::__construct() must implement interface pocketmine\inventory\InventoryHolder, instance of pocketmine\math\Vector3 given, called in phar:///home/arma/plugins/VirtualChest_v1.1.5.phar/src/presentkim/virtualchest/inventory/VirtualChestInventory.php on line 1`

`[00:24:42] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\inventory\BaseInventory::__construct() must implement interface pocketmine\inventory\InventoryHolder, instance of pocketmine\math\Vector3 given, called in phar:///home/arma/plugins/VirtualChest_v1.1.5.phar/src/presentkim/virtualchest/inventory/VirtualChestInventory.php on line 1" (EXCEPTION) in "src/pocketmine/inventory/BaseInventory" at line 57`

This happen after do /vc set {player name} 23 and /vc open

**Comment by PresentKim** [comment]
I changed construct argument for support to pmmp/PocketMine-MP@2fb580d

You can fix it by using the later version of the pmmp/PocketMine-MP@2fb580d

(See -> PMMPPlugin/VirtualChest@e5f12f6)
