### ISSUE TITLE
/vchest open does not work

### ISSUE THREAD

**Issue by Matthieu05** [PMMPPlugin/VirtualChest#2]
When I do **/vchest open**, I get the error 

> This command failed due to an unknown error

**Comment by armagadon159753** [comment]
Check if plugin is loaded

**Comment by Matthieu05** [comment]
The plugin is enabled

**Comment by armagadon159753** [comment]
Try the newest version and plz send more information:
Commit: 
How to reproduce step by step 
Etc...

**Comment by Matthieu05** [comment]
I'm using the latest version # 12.
 I did :
-/vchest default 1
-/vchest save
-/vchest reload
-/vchest open -----> Error
I have restart the server
/vchest set Matthieu005 1
/vchest save
/vchest reload
/vchest open 1 ---->Error
/vchest view Matthieu005 ----->Error

**Comment by PresentKim** [comment]
@Matthieu05 Can you try this release? https://github.com/PMMPPlugin/VirtualChest/releases/tag/v1.1.7

(And please give me that error message)
